version: 1.0.{build}

#
# Skipping commits affecting these files.
#
skip_commits:
   files:
    - '**/*.md'
    - '**/*.png'
    - '**/*.jpg'

environment:
  # global:
  #   CL: -nologo -MP
  matrix:
    - CPU: x86
    - CPU: x64

matrix:
  #
  # Immediately finish build if one of the above jobs fails.
  #
  fast_finish: true

install:
  #
  # Set compiler environment for MSVC first.
  #
  - cmd: call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %CPU%

build_script:
  - cmd: CI\appveyor-script.bat init
  - cmd: cd src
  - cmd: set USE_LUAJIT=1
  - cmd: set PLATFORM=%CPU%

  - cmd: nmake -nologo -f Makefile.vc6

test_script:
  - cmd: set WSOCK_TRACE_LEVEL=1 & ws_tool.exe test -v
  - cmd: set WSOCK_TRACE_LEVEL=0 & set USE_LUAJIT=0

  #
  # Delete '..\IPFire-database.db' to force a download and decompression
  # in the 'ws_tool.exe asn -u' command.
  #
  - cmd: del /Q ..\IPFire-database.db
  - cmd: set WSOCK_TRACE_LEVEL=1 & ws_tool.exe asn -u
  - cmd: set WSOCK_TRACE_LEVEL=0 & ws_tool.exe idna -c 1252 räksmörgås.se öbb.at bücher.ch
  - cmd: set WSOCK_TRACE_LEVEL=0 & geoip-test.bat -4
  - cmd: set WSOCK_TRACE_LEVEL=0 & geoip-test.bat -6

  #
  # A simple test of the 'mhook' code:
  #
  # - cmd: set WSOCK_TRACE_LEVEL=1 & mhook-test.exe

#
# Create a %ZIP_FILE% of the files needed to run the produced .exe-files (no source-files).
#
# after_test:
#   - cmd: set ZIP_FILE=wsock_trace-%CPU%-%APPVEYOR_BUILD_NUMBER%.zip
#   - cmd: 7z a %ZIP_FILE% .\README.md  .\wsock_trace .\geoip .\geoip6 .\drop.txt .\dropv6.txt .\edrop.txt src\*.dll src\*.pdb src\*.lib src\*.a src\*.exe src\*.lua > NUL

#
# Push %ZIP_FILE% as an artifact.
# (cannot use the ZIP_FILE env-var here!)
#
# artifacts:
#   - path: wsock_trace-%CPU%-%APPVEYOR_BUILD_NUMBER%.zip
#     name: Wsock-Trace

#
# Try to preserve previously downloaded stuff in 'CI-temp'.
#
cache:
  - 'C:\projects\wsock-trace\CI-temp'

