version: 1.0.{build}

#
# Skipping commits affecting these files.
#
skip_commits:
   files:
    - '**/*.md'
    - '**/*.png'
    - '**/*.jpg'

environment:
  # global:
  #   CL: -nologo -MP
  matrix:
    - BUILDER: msvc
      CPU:     x86
    - BUILDER: msvc
      CPU:     x64
    - BUILDER: mingw
      CPU:     x86
    - BUILDER: mingw
      CPU:     x64
    - BUILDER: cygwin
      CPU:     x86
    - BUILDER: cygwin
      CPU:     x64
    - BUILDER: watcom
      CPU:     x86

matrix:
  #
  # Immediately finish build if one of the above jobs fails.
  #
  fast_finish: true
  allow_failures:
     - BUILDER: watcom
     - BUILDER: cygwin

#
# todo: Get better version string.
#
cache:
  - wsock-trace-%APPVEYOR_BUILD_NUMBER%

before_build:
  #
  # Download IP+ASN Databases and decompress using '7z'.
  # But do not download and decompress 'location.db.xz'.
  # Let 'ASN_check_and_update()' do it at run-time.
  #
  - cmd: curl -O -# http://www.watt-32.net/CI/IP46-COUNTRY.BIN.xz
  - cmd: curl -O -# http://www.watt-32.net/CI/IP4-ASN.CSV.xz
  - cmd: curl -O -# http://www.watt-32.net/CI/IP6-ASN.CSV.xz
  - cmd: 7z x IP46-COUNTRY.BIN.xz > NUL
  - cmd: 7z x IP4-ASN.CSV.xz      > NUL
  - cmd: 7z x IP6-ASN.CSV.xz      > NUL

install:
  #
  # Add a few locations to our PATH.
  # And setup the compiler environment for Watcom
  # (it seems it cannot be done in 'appveyor-script.bat init')
  #
  - cmd: set WATCOM=%CD%\watcom
  - cmd: set PATH=%CD%\src;%WATCOM%\binnt;%PATH%
  - cmd: set NT_INCLUDE=%WATCOM%\h;%WATCOM%\h\nt
  - cmd: set DISABLEDELAYEDEXPANSION=0
  - cmd: set CYGWIN_OPT=-qgnNdOA -l c:\cygwin\var\cache\setup -R c:\cygwin -s http://cygwin.mirror.constant.com

  #
  # Set compiler environment for MSVC first.
  #
  - cmd: if %BUILDER%.       == msvc.       call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %CPU%
  - cmd: if %BUILDER%-%CPU%. == mingw-x86.  set PATH=c:\msys64\MinGW32\bin;c:\msys64\usr\bin;%PATH%
  - cmd: if %BUILDER%-%CPU%. == mingw-x64.  set PATH=c:\msys64\MinGW64\bin;c:\msys64\usr\bin;%PATH%
  - cmd: if %BUILDER%-%CPU%. == cygwin-x86. c:\cygwin\setup-x86.exe %CYGWIN_OPT% > NUL & set PATH=c:\cygwin\bin;c:\msys64\usr\bin;%PATH%
  - cmd: if %BUILDER%-%CPU%. == cygwin-x64. set PATH=c:\msys64\usr\bin;%PATH%

build_script:
  - cmd: appveyor-script.bat init

  #
  # Download and extract OpenWatcom 2.0 using 'curl'
  #
  - cmd: if %BUILDER%. == watcom. (
            curl -O -# http://www.watt-32.net/CI/watcom20.zip &
            7z x -o%WATCOM% watcom20.zip > NUL)

  - cmd: cd src
  - cmd: set USE_LUA=1
  - cmd: set PLATFORM=%CPU%
  - cmd: set CYGWIN=nodosfilewarning

  - cmd: if %BUILDER%. == msvc.   nmake -nologo -f Makefile.vc6
  - cmd: if %BUILDER%. == mingw.  make          -f Makefile.MinGW  CPU=%CPU%
  - cmd: if %BUILDER%. == cygwin. make          -f Makefile.CygWin CPU=%CPU%
  - cmd: if %BUILDER%. == watcom. wmake -h      -f Makefile.Watcom CPU=%CPU%
  - cmd: set USE_LUA=0

test_script:
  - cmd: set WSOCK_TRACE_LEVEL=1 & set USE_LUA=1 & ws_tool.exe test -v & set USE_LUA=0 & set WSOCK_TRACE_LEVEL=0

  #
  # Delete '..\IPFire-database.db' to force a download and decompression.
  # Since now it's not done via 'DllMain()', it should be safe.
  #
  - cmd: if not %BUILDER%. == watcom. del /Q ..\IPFire-database.db
  - cmd: geoip-test.bat -4
  - cmd: geoip-test.bat -6

#
# Create a %ZIP_FILE% of the files needed to run the produced .exe-files (no source-files).
# Prevent the 'watcom' directory to end up in 'artifacts'.
#
# after_test:
#   - cmd: set ZIP_FILE=wsock_trace-%BUILDER%-%CPU%-%APPVEYOR_BUILD_NUMBER%.zip
#   - cmd: if %BUILDER%. == watcom. (echo Removing Watcom tree & rm -fR watcom/* & rmdir watcom)
#   - cmd: 7z a %ZIP_FILE% .\README.md  .\wsock_trace .\geoip .\geoip6 .\drop.txt .\dropv6.txt .\edrop.txt src\*.dll src\*.pdb src\*.lib src\*.a src\*.exe src\*.lua > NUL

#
# Push %ZIP_FILE% as an artifact.
# (cannot use the ZIP_FILE env-var here!)
#
# artifacts:
#   - path: wsock_trace-%BUILDER%-%CPU%-%APPVEYOR_BUILD_NUMBER%.zip
#     name: Wsock-Trace

